### ISSUE TITLE
404 issue

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/keyserver#25]
Chat is broken when using the sample apps.
Console is showing 404's

@devceline Suspected cache
@Elyniss Said it relates to AWS

cc @arein 

To repro: start using https://react-wallet-chat.walletconnect.com/ 

<img width="658" alt="Screenshot 2022-11-29 at 14 07 46" src="https://user-images.githubusercontent.com/116099/204538658-016a6721-b97d-47c6-8989-0d3e0e169fb1.png">

**Comment by Elyniss** [comment]
The issue was having two instances of keyserver with still having in-memory data store. Solved by reducing number of instances to one

**Comment by arein** [comment]
Fixed
See threads
Apologies
